# Generated by Django 5.1.3 on 2024-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhevents', '0002_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
