# Generated by Django 5.1.3 on 2024-12-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hhHobbies", "0001_initial"),
        ("hhevents", "0003_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hobby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="hhHobbies.hobby",
            ),
        ),
    ]
