# Generated by Django 4.2.16 on 2024-11-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhPosts', '0002_post_user_alter_post_caption_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='posts_media/'),
        ),
    ]
