# Generated by Django 5.1.3 on 2024-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hhHobbies", "0001_initial"),
        ("hhPosts", "0004_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="hhHobbies.hobby"
            ),
        ),
    ]
