# Generated by Django 5.1.3 on 2024-12-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hhPosts", "0005_post_hobbies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
